// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ysKGJDXbDao1fBX5yYju0bF7eFAHKqA',
    appId: '1:931939716590:web:ee31bdf4d2a15c918592ff',
    messagingSenderId: '931939716590',
    projectId: 'bulletnews-fb8ae',
    authDomain: 'bulletnews-fb8ae.firebaseapp.com',
    storageBucket: 'bulletnews-fb8ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPPGG8PIEE4B0kTy-sfXaN6PCiJnuojeo',
    appId: '1:931939716590:android:0a8ac3bfad5a54c08592ff',
    messagingSenderId: '931939716590',
    projectId: 'bulletnews-fb8ae',
    storageBucket: 'bulletnews-fb8ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMoCdXn31zwbb4xtejpjlgTlYcRUscpgY',
    appId: '1:931939716590:ios:54908edc2e1a47228592ff',
    messagingSenderId: '931939716590',
    projectId: 'bulletnews-fb8ae',
    storageBucket: 'bulletnews-fb8ae.appspot.com',
    androidClientId: '931939716590-f0p2hos64pcds7k223jmpq2u9cc9qmsm.apps.googleusercontent.com',
    iosClientId: '931939716590-vkvqqsh4745m0u1u8n5ssuakea939u98.apps.googleusercontent.com',
    iosBundleId: 'com.example.bulletNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMoCdXn31zwbb4xtejpjlgTlYcRUscpgY',
    appId: '1:931939716590:ios:fb22bf224b3abab78592ff',
    messagingSenderId: '931939716590',
    projectId: 'bulletnews-fb8ae',
    storageBucket: 'bulletnews-fb8ae.appspot.com',
    androidClientId: '931939716590-f0p2hos64pcds7k223jmpq2u9cc9qmsm.apps.googleusercontent.com',
    iosClientId: '931939716590-4jdds87upkkfvmdbol3tij7hiqp6ptto.apps.googleusercontent.com',
    iosBundleId: 'com.example.bulletNews.RunnerTests',
  );
}
